apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-prod
  namespace: n8n-prod
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-prod
            port:
              number: 5678
