apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-prod
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-prod

  source:
    repoURL: https://github.com/mactruitasse/poc-playwrite.git
    targetRevision: main
    path: charts/n8n

    helm:
      valueFiles:
        - ../../apps/n8n/values-prod.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
